jobs:
  close-pending:
    name: close-pending
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.repository == 'apache/ozone'
      name: Execute close-pending script
      run: ./.github/close-pending.sh
name: close-prs
on:
  repository_dispatch:
    types: trigger-ga___close-pending.yaml
