concurrency:
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  group: dependabot-ci-${{ github.event.pull_request.number || github.sha }}
jobs:
  dependabot-check:
    env:
      CI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_VERSION: 16.14.2
      PNPM_URL: https://get.pnpm.io/install.sh
      PNPM_VERSION: 7.33.6
      cURL_ARGS: -fsSL
      cURL_LOC: /usr/bin/curl
    if: ${{ github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
      && startsWith(github.event.pull_request.title, '[Recon] Dependabot Package Upgrade')
      }}
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: get_branch_name
      name: Extract branch name
      run: echo "branch_name=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      shell: bash
    - continue-on-error: true
      name: Checkout dependabot branch
      uses: actions/checkout@v4
      with:
        path: ozone
        ref: ${{ github.event.pull_request.head.sha }}
    - continue-on-error: true
      name: Delete the lockfile
      run: '#Delete the lockfile created by dependabot

        rm -rf hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/pnpm-lock.yaml

        '
      working-directory: ozone
    - continue-on-error: true
      name: Install NodeJS v${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - continue-on-error: true
      name: Install pnpm v${{ env.PNPM_VERSION }} and recreate lockfile
      run: '# Install PNPM and recreate lockfile

        echo "Fetching pnpm from $PNPM_URL with version $PNPM_VERSION"

        $cURL_LOC $cURL_ARGS $PNPM_URL | env PNPM_VERSION=$PNPM_VERSION SHELL="$(which
        sh)" ENV="$HOME/.shrc" sh -

        source /home/runner/.shrc

        PNPM_EXEC=$(which pnpm)

        echo "pnpm is present at: $PNPM_EXEC"

        $PNPM_EXEC config set store-dir ~/.pnpm-store

        cd hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/

        $PNPM_EXEC install --lockfile-only

        '
      shell: bash
      working-directory: ozone
    - continue-on-error: true
      name: Commit generated lockfile
      run: 'OZONE_SHA=$(git -C ./ rev-parse HEAD)

        cd hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/

        git add ./pnpm-lock.yaml

        git status

        git config --global user.name ''Github Actions''

        git config --global user.email ''noreply@github.com''

        git commit -m "[auto] Generated pnpm-lock from actions for $OZONE_SHA" ||
        true

        git push origin HEAD:${{ steps.get_branch_name.outputs.branch_name }}

        '
      working-directory: ozone
    timeout-minutes: 15
name: dependabot-ci
on:
  repository_dispatch:
    types: trigger-ga___dependabot-ci.yml
