jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout project
      uses: actions/checkout@v4
    - continue-on-error: true
      id: restore-cache
      name: Restore cache for Maven dependencies
      uses: actions/cache/restore@v4
      with:
        key: maven-repo-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository/*/*/*

          !~/.m2/repository/org/apache/ozone

          '
    - continue-on-error: true
      if: steps.restore-cache.outputs.cache-hit != 'true'
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      if: steps.restore-cache.outputs.cache-hit != 'true'
      name: Fetch dependencies
      run: mvn --batch-mode --fail-never --no-transfer-progress --show-version -Pgo-offline
        -Pdist clean verify
    - continue-on-error: true
      if: steps.restore-cache.outputs.cache-hit != 'true'
      name: Delete Ozone jars from repo
      run: rm -fr ~/.m2/repository/org/apache/ozone
    - continue-on-error: true
      if: steps.restore-cache.outputs.cache-hit != 'true'
      name: List repo contents
      run: find ~/.m2/repository -type f | sort | xargs ls -lh
    - continue-on-error: true
      if: steps.restore-cache.outputs.cache-hit != 'true'
      name: Save cache for Maven dependencies
      uses: actions/cache/save@v4
      with:
        key: maven-repo-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository/*/*/*

          !~/.m2/repository/org/apache/ozone

          '
name: populate-cache
on:
  repository_dispatch:
    types: trigger-ga___populate-cache.yml
