concurrency:
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  group: ci-${{ github.event.pull_request.number || github.sha }}
jobs:
  CI:
    if: github.event_name == 'pull_request' || !startsWith(github.ref_name, 'dependabot')
    secrets: inherit
    uses: ./.github/workflows/ci.yml
name: build-branch
on:
  repository_dispatch:
    types: trigger-ga___post-commit.yml
