jobs:
  title:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout project
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        TITLE: ${{ github.event.pull_request.title }}
      name: Check pull request title
      run: dev-support/ci/pr_title_check.sh "${TITLE}"
name: pull request
on:
  repository_dispatch:
    types: trigger-ga___pull-request.yml
